# Generated by Django 3.2.5 on 2021-07-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('surname', models.CharField(blank=True, max_length=20)),
                ('bday', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MailingReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('received_date', models.DateField()),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailapp.mailinglist')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailapp.receiver')),
            ],
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='receivers',
            field=models.ManyToManyField(to='emailapp.Receiver'),
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, unique=True)),
                ('mailing_date', models.DateField(auto_now=True)),
                ('mailing_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailapp.mailinglist')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
