# Generated by Django 3.2.5 on 2021-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_auto_20210715_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_subject',
            field=models.CharField(default='', max_length=30),
        ),
    ]
