# Generated by Django 3.2.5 on 2021-07-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_auto_20210713_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_status',
            field=models.BooleanField(default=False),
        ),
    ]
