# Generated by Django 3.2.5 on 2021-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_mailing_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
